name: Update dependencies

on: 
  schedule:
  # At 20:00 UTC on Tuesday.
  - cron: '00 20 * * 2'
  
  repository_dispatch:
    types: update-dependencies

  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update dependencies
    uses: CCSWE-nanoframework/actions-nanoframework/.github/workflows/update-dependencies.yml@master
    secrets: inherit
    with:
      solution: 'CCSWE.nanoFramework.NeoPixel.sln'
      branchToPr: 'master'
